---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pods-viewer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
    - get
    - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-lister-account
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pods-lister-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pods-viewer
subjects:
- kind: ServiceAccount
  name: pods-lister-account
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "pods-lister"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pods-lister
    spec:
      serviceAccount: pods-lister-account
      containers:
      - name: app
        image: "rafaelcaricio/pods-lister:0.2.0"
